[project]
name = "llm-app"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pillow>=11.3.0",
    "torch>=2.2.2",
    "torchtext>=0.17.2",
    "torchvision>=0.17.2",
    "transformers>=4.56.1",
]
